import { v } from "convex/values";
import { mutation, query } from "./_generated/server";

const SHOW_COMMENTS = true;

export const list = query({
  args: { chatId: v.id("chats") },
  handler: async (ctx, args) => {
    // const identity = await ctx.auth.getUserIdentity();
    // if (!identity) {
    //   throw new Error("Not authenticated");
    // }

    const messages = await ctx.db
      .query("messages")
      .withIndex("by_chatId", (q) => q.eq("chatId", args.chatId))
      .order("asc")
      .collect();

    if (SHOW_COMMENTS) {
      console.log("📜 Retrieved messages:", {
        chatId: args.chatId,
        count: messages.length,
      });
    }

    return messages;
  },
});

export const send = mutation({
  args: {
    chatId: v.id("chats"),
    content: v.string(),
  },
  handler: async (ctx, args) => {
    if (SHOW_COMMENTS) {
      console.log("📤 Sending message:", {
        chatId: args.chatId,
        content: args.content,
      });
    }

    // const identity = await ctx.auth.getUserIdentity();
    // if (!identity) {
    //   throw new Error("Not authenticated");
    // }

    // const chat = await ctx.db.get(args.chatId);
    // if (!chat || chat.userId !== identity.subject) {
    //   throw new Error("Unauthorized");
    // }

    // Save the user message with preserved newlines
    const messageId = await ctx.db.insert("messages", {
      chatId: args.chatId,
      content: args.content.replace(/\n/g, "\\n"),
      // Note: role field is not in the schema, so we're storing it in the content
      // We'll need to update the schema if we want to properly store the role
      userId: "user", // Using userId field to indicate role
      createdAt: Date.now(),
    });

    if (SHOW_COMMENTS) {
      console.log("✅ Saved user message:", {
        messageId,
        chatId: args.chatId,
      });
    }

    return messageId;
  },
});

export const store = mutation({
  args: {
    chatId: v.id("chats"),
    content: v.string(),
    role: v.union(v.literal("user"), v.literal("assistant")),
  },
  handler: async (ctx, args) => {
    if (SHOW_COMMENTS) {
      console.log("💾 Storing message:", {
        chatId: args.chatId,
        role: args.role,
        contentLength: args.content.length,
      });
    }

    // For very large content, consider chunking or compression strategies
    const processedContent = args.content;
    
    // Check if content is extremely large
    if (processedContent.length > 100000) {
      console.warn("⚠️ Very large message content detected:", processedContent.length, "characters");
    }

    // Store message with preserved newlines and HTML
    const messageId = await ctx.db.insert("messages", {
      chatId: args.chatId,
      content: processedContent
        .replace(/\n/g, "\\n")
        // Don't escape HTML - we'll trust the content since it's generated by our system
        .replace(/\\/g, "\\\\"), // Only escape backslashes
      userId: args.role === "assistant" ? "assistant" : "user", // Using userId field to indicate role
      createdAt: Date.now(),
    });

    if (SHOW_COMMENTS) {
      console.log("✅ Stored message:", {
        messageId,
        chatId: args.chatId,
        role: args.role,
      });
    }

    return messageId;
  },
});

export const getLastMessage = query({
  args: { chatId: v.id("chats") },
  handler: async (ctx, args) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) {
      throw new Error("Not authenticated");
    }

    const chat = await ctx.db.get(args.chatId);
    if (!chat || chat.userId !== identity.subject) {
      throw new Error("Unauthorized");
    }

    // Use a more specific index query with limit
    const messages = await ctx.db
      .query("messages")
      .withIndex("by_chatId", (q) => q.eq("chatId", args.chatId))
      .order("desc")
      .take(1);

    return messages[0];
  },
});